/**
 *
 * $Id$
 */
package Bowling.validation;

import Bowling.Matchup;
import Bowling.Player;

/**
 * A sample validator interface for {@link Bowling.Game}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GameValidator {
	boolean validate();

	boolean validatePlayer(Player value);

	boolean validateFrames(int value);

	boolean validateMatchup(Matchup value);
}
