/**
 *
 * $Id$
 */
package Bowling.validation;

import java.util.Date;

/**
 * A sample validator interface for {@link Bowling.Player}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlayerValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDateOfBirth(Date value);
	boolean validateHeight(double value);
	boolean validateIsProfessional(boolean value);
}
