/**
 *
 * $Id$
 */
package Bowling.validation;

import Bowling.Matchup;
import Bowling.TournamentType;

/**
 * A sample validator interface for {@link Bowling.Tournament}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TournamentValidator {
	boolean validate();

	boolean validateMatchup(Matchup value);
	boolean validateType(TournamentType value);
}
